### ISSUE TITLE
Error with installation

### ISSUE THREAD

**Issue by jcoludar** [macmanes-lab/orp_website#1]
Hi guys, I am trying to install ORP as a conda env following the steps suggested in the manual. However, while running make command (with sudo), I've encountered this error:

curl: (13) Bad PASV/EPSV response: 500
make: *** [Makefile:73: diamond_data] Error 13

The lines right before that are:

cd /media/jcoludar/Daten/Ivan/Software/Oyster_River_Protocol/software/diamond && curl -LO ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz && gzip -d uniprot_sprot.fasta.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0

Would be great if you can suggest a way to solve this.

Thanks!

Ivan

**Comment by macmanes** [comment]
This is a network connectivity error either on your side or Uniprot.

Matt


On Mar 9, 2020, at 06:46, jcoludar <notifications@github.com<mailto:notifications@github.com>> wrote:

Caution - External Email
________________________________

Hi guys, I am trying to install ORP as a conda env following the steps suggested in the manual. However, while running make command (with sudo), I've encountered this error:

curl: (13) Bad PASV/EPSV response: 500
make: *** [Makefile:73: diamond_data] Error 13

The lines right before that are:

cd /media/jcoludar/Daten/Ivan/Software/Oyster_River_Protocol/software/diamond && curl -LO ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz<https://urldefense.proofpoint.com/v2/url?u=ftp-3A__ftp.uniprot.org_pub_databases_uniprot_current-5Frelease_knowledgebase_complete_uniprot-5Fsprot.fasta.gz&d=DwQCaQ&c=c6MrceVCY5m5A_KAUkrdoA&r=lFmSBplGfvpPNKk6W2tN6-UcUrgjlsdpj7JuHtA6g_Y&m=1Hkx8Ilt64hLlUBJv0dMzp9AbHOcDcBqHnSEbzyHAOw&s=eqeRQOZqRaK16uopsfXdEb00p3lHdWschiJSNz8vWI0&e=> && gzip -d uniprot_sprot.fasta.gz
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- 0:00:01 --:--:-- 0

Would be great if you can suggest a way to solve this.

Thanks!

Ivan

**Comment by jcoludar** [comment]
Thank you!
